version: '3'
services:
  app:
    container_name: sysos-app
    build: ./docker/php-fpm
    restart: unless-stopped
    volumes:
      - ./docker/php-fpm/conf.d:/usr/local/etc/php/conf.d
      - .:/application
      - data:/application/public/cvs
    networks:
      - interna

  web:
    container_name: sysos-web
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=sysos.rochamarinho.adv.br
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/application/public
      - data:/application/public/cvs
    networks:
      - interna
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.sysos-prefix.stripprefix.prefixes=/sysos
      - traefik.http.routers.sysos.entrypoints=http
      - traefik.http.routers.sysos.middlewares=sysos-prefix
      - traefik.http.routers.sysos.rule=Host(`homologacao.rochamarinho.adv.br`) && PathPrefix(`/sysos`)

networks:
  interna:
    external: true

volumes:
  data:
